### ISSUE TITLE
What is the intent of a time series database?

### ISSUE THREAD

**Issue by jayrmotta** [spotify/heroic#11]
I work on an education startup and content engagement is a great concern for us, I've been thinking how can I know if a given user has engaged with a video or an audio. Is it an arbitraty percentage of content consumed? How can I store the moments of content consumed, which moment has been consumed more than one time, etc.

Is this database or this category of database something I should be looking into to solve this kind of problem?

**Comment by udoprog** [comment]
Hey,

You might want to give [Wikipedia a read](https://en.wikipedia.org/wiki/Time_series_database). It's indeed a type of database specialized towards storing time series data. Simplified, it's typically specialized towards measuring and analyzing something over time.
It sounds like your problem can be addressed by this kind of database, Heroic might be a poor fit unless you are looking to setup a very large solution since that is what it specializes towards.

Good luck with your startup!
