### ISSUE TITLE
Poor write performance (BigTable)

### ISSUE THREAD

**Issue by mykolasmith** [spotify/heroic#114]
Hi,

First off wanted to say thank you for open sourcing this excellent project. Our company migrated to Google Cloud Platform specifically for the benefits afforded by BigTable, and we're really happy to see Heroic being built w/ support for it from the outset. We are currently using OpenTSDB in production, but the BigTable adapter is pretty alpha and some important features, such as deleting data, are unsupported at the moment.

With OpenTSDB, we are seeing latencies ~30-40ms for writing 60 points to a series. With Heroic, however, we are seeing performance ~10x slower, ranging from 300-400ms for writing the exact same data. Both services are running on a single node in Google Compute Engine (4 vCPUs, 15 GB). I have included below the API calls to both Heroic and OpenTSDB, as well as a screengrab from our Grafana dashboard that shows the difference in latency.

It might be worth mentioning that we are seeing good read times. It only appears that writes are slower than OpenTSDB.

![screen shot 2016-10-20 at 11 17 13 am 2](https://cloud.githubusercontent.com/assets/1483054/19566061/ff1f80bc-96b6-11e6-96df-acd2ee97a021.png)

![screen shot 2016-10-20 at 11 18 22 am](https://cloud.githubusercontent.com/assets/1483054/19566068/05d268fc-96b7-11e6-9d54-16f375c1d97a.png)

![screen shot 2016-10-20 at 11 18 43 am](https://cloud.githubusercontent.com/assets/1483054/19566077/09ba5dd0-96b7-11e6-891b-8955b5d3b634.png)

**Comment by udoprog** [comment]
In Heroic the `/write` endpoint blocks until the data has been committed both in Elasticsearch* and Bigtable.

These could be potential explanations:

1. The Elasticsearch* index operation might take a bit of time. This has a write-through cache that can be enabled so that [only the first write will suck every n minutes](http://spotify.github.io/heroic/#!/docs/config/metadata), you should attempt to route writes to the same node as much as possible to help this out.
2. Some layer in OpenTSDB/HBaseClient performs batching, and you are not seeing the roundtrip to Bigtable - only the time it takes to queue up the write.
3. Heroic issues individual mutations for every datapoint in parallel, and we are hitting some resource constraint/issue regarding that.

*: assuming you have it configured to use Elasticsearch.

I don't think option 2 is very likely, 36 ms seems around the time I'd expect it to be (assuming the API node lives in the same region). The query path supports tracing. We could add something similar to the write path as well to get better insights.

In general we are aiming at supporting sustained throughput over individual request latency. So you should expect to have a couple pending in-flight writes at all times. I'd recommend making use of HTTP/2 to multiplex these over a single connection or to use a queue (like Kafka) that acts as a buffer.

@juruen is also working on incorporating a batch writer provided by the client library which in our experiments has improved throughput quite a bit. In it's current implementation it would probably not help much regarding the latency for individual writes. The batches are flushed every two seconds by default, and your latency would depend on how well you hit that window. But we might implement a looser consistency guarantee with this that would queue up writes instead of committing them. This would run the risk of losing some acked writes if the node goes down but provide better latency.

**Comment by juruen** [comment]
Actually, bulk mutations are already in master as of bc82c27be83db2a39a3a3b2a9a2a4b73bc863bac

Batches are automatically flushed when they reach 25 metrics (bigtable client 0.9.3) or 100 metrics (bigtable client 0.9.2), otherwise they will get flushed after 2 seconds.

Depending on how you are generating your metrics in your test and which BT client library is being used, it may have an impact on latency.
