### ISSUE TITLE
DELETE: /metadata/series

### ISSUE THREAD

**Issue by luluprat** [spotify/heroic#149]
hey,

when i try to delete series nothing happens

```
curl -X DELETE -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: cd696223-8dbd-946b-1153-8c12e88242bb" -d '{"filter":  ["key", "nsa"]}' "http://rsdb:8080/metadata/series"
{"errors":[],"deleted":0,"failed":0}
```

**Comment by udoprog** [comment]
It could simply be that accounting (the deleted and failed counts) are not correct.
I believe this can be fixed with #75, but note that for some backends the counts are not supported at all.
This should however be communicated better.

Can you verify if the documents are actually being deleted by trying to query for them again after the delete call?

**Comment by lucilecoutouly** [comment]
it is deleted from queries
but it is still in elasticsearch and cassandra

**Comment by hexedpackets** [comment]
Closing due to age, feel free to re-open if this is still an issue.
