### ISSUE TITLE
chain filter or complexe filter

### ISSUE THREAD

**Issue by coutouly** [spotify/heroic#242]
Hello ,

i am trying to use filter 
what i want in the and is all data where a tag is between tow values
example:
i put some data into heroic (kafka)
```
{"host":"nsadb","version":"1.0.0","key":"nsa","time":1357128005000,"attributes":{"idg":"para610","az":"100.8","si":"0.3","polar":"VL","c":"C0000","nconf":"1","f":"601000000"},"value":-95.7855361596}
```

my request is like

```
{
	"groupBy": ["f"], 
	"source": "points", 
	"range": {"type": "absolute", "start": 1357726500000, "end": 1357726860000}, 
	"aggregation": {"type": "average", "size": {"duration": 10, "unit": "SECONDS"}}, 
	"filter": ["and", ["key", "nsa"],["^","f","1000000"] ]
}
```
because i want all f values : from 600000000 to 1205000000 i have to write a lot of query with f incrementing

```
"filter": ["and", ["key", "nsa"],["^","f","600000000"] ]}

"filter": ["and", ["key", "nsa"],["^","f","700000000"] ]}
"filter": ["and", ["key", "nsa"],["^","f","800000000"] ]}
"filter": ["and", ["key", "nsa"],["^","f","900000000"] ]}
…

"filter": ["and", ["key", "nsa"],["^","f","1204000000"] ]}
```

is there a way to simplify the query filter ?

chaining or complexifying ?

thanks

**Comment by udoprog** [comment]
No, due to the way filters are implemented only prefixes and exact matches are efficiently supported.

Doing what you propose would require more analysis of the tag by treating it as a [number](https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html) or a [range](https://www.elastic.co/guide/en/elasticsearch/reference/current/range.html), and support a range filter. Currently not supported, but by no means impossible.

**Comment by lucilecoutouly** [comment]
ok 

i see a regex filter ^

is it possible to test it ?

thanks

**Comment by hexedpackets** [comment]
Closing due to age, feel free to re-open if this is still an issue.
