### ISSUE TITLE
elasticsearch index

### ISSUE THREAD

**Issue by lucilecoutouly** [spotify/heroic#377]
hello
I was wondering which is better to use : 
- rotate index by day or week
- fixed index 

what i will have in heroic will stay inside for years AND i want to be able to query heroic over 10 years of data ...
any advice will be appreciate 
thanks
Lucile

**Comment by dmichel1** [comment]
hi @lucilecoutouly 

At Spotify we rotate the index weekly and keep 2 indexes. The API is configured to query both indexes for reads. The reason for the weekly rotations is mostly because of the size of the data in ES. 

The size of the ES cluster for suggestions is around 1 TB  for the index and 2B+ documents!

The size of the ES cluster for metadata is around 40GB for the index and 160M+ documents. 

We have talked about potentially keeping more metadata indexes around to allow older time series to still be accessed but it might be confusing without suggestions.

If you are able to store the amount of data in a single index I would go for that option.
