### ISSUE TITLE
Cassandra & Data retention questions

### ISSUE THREAD

**Issue by yarinb** [spotify/heroic#52]
I know this is not the appropriate place for questions but with the lack of a mailing list or gitter channel - I think it's forgivable (feel free to delete if not).

I'm setting up a VM with heroic in order to monitor some of our homegrown metrics (ingesting metric with the REST API into heroic) and got some questions for which I couldn't find any answers on Wiki and homepage.
1. Data retention - Is this configurable somehow? Ideally - I'd like to store 7 days of raw data and than store pre-aggregated series for as long as we need them (year maybe?)
2. Cassandra fetching - Any reason heroic is doing multiple fetches based on range segments? I'm not too familiar with Cassandra so it's probably a dumb question. What's wrong with doing one query that returns all rows vs. multiple queries?

Thanks!

**Comment by udoprog** [comment]
No worries.

Multiple fetches are used because tone series spans across multiple rows, and they have to be fetched one at a time.

Data retention can be configured as a TTL fit C*. Roll-ups are not supported. All though if implemented it would most likely be part of a garbage collection process that also sorry flexible retention.
Problem is just that deleting data outside of TTLs is so hard with C*.

**Comment by yarinb** [comment]
Thanks for your response!
Just to understand the schema - Isn't each metric occupying one row? How come one metric (with its row key) can span multiple rows?

**Comment by udoprog** [comment]
It's to avoid filling a single partition with more than the max number of cells:
http://wiki.apache.org/cassandra/CassandraLimitations
